cargo-features = ["rename-dependency"]

[package]
name = "tarpc-compat"
version = "0.1.0"
authors = ["Tim <tikue@google.com>"]
edition = "2018"

[dependencies]
futures_legacy = { version = "0.1", package = "futures" }
futures-preview = { version = "0.3.0-alpha.9", features = ["compat"] }
